# https://github.com/openai/codex/blob/main/docs/config.md

approval_policy = "on-request"
sandbox_mode = "danger-full-access"

[tools]
web_search = true

[model_providers.lmstudio]
name = "LM Studio"
base_url = "http://192.168.1.5:114/v1"

[profiles.gpt-5]
model = "gpt-5"
model_reasoning_effort = "high"

[profiles.gpt-5-codex]
model = "gpt-5-codex"
model_reasoning_effort = "high"

[profiles.gpt-oss-120b]
model_provider = "lmstudio"
model = "openai/gpt-oss-120b"
model_reasoning_effort = "high"

[profiles.qwen3-coder-30b]
model_provider = "lmstudio"
model = "qwen/qwen3-coder-30b"

[profiles.qwen3-next-80b]
model_provider = "lmstudio"
model = "qwen/qwen3-next-80b"
