/**
 * Mock data for WEC Live Timing
 * Simulates real race data with realistic timing information
 */

export const mockChampionships = [
  {
    id: 'wec-2025',
    name: 'FIA World Endurance Championship',
    season: 2025,
    logo: '/logos/wec.png',
    races: ['qatar-2025', 'imola-2025', 'spa-2025', 'lemans-2025'],
  },
];

export const mockCircuits = {
  'lusail': {
    id: 'lusail',
    name: 'Lusail International Circuit',
    country: 'Qatar',
    countryCode: 'QA',
    length: 5.419,
  },
  'imola': {
    id: 'imola',
    name: 'Autodromo Enzo e Dino Ferrari',
    country: 'Italy',
    countryCode: 'IT',
    length: 4.909,
  },
  'spa': {
    id: 'spa',
    name: 'Circuit de Spa-Francorchamps',
    country: 'Belgium',
    countryCode: 'BE',
    length: 7.004,
  },
  'lemans': {
    id: 'lemans',
    name: 'Circuit de la Sarthe',
    country: 'France',
    countryCode: 'FR',
    length: 13.626,
  },
};

export const mockDrivers = [
  // Ferrari #50
  { id: 'd1', firstName: 'Antonio', lastName: 'Fuoco', shortName: 'FUO', countryCode: 'IT', category: 'PLATINUM' },
  { id: 'd2', firstName: 'Miguel', lastName: 'Molina', shortName: 'MOL', countryCode: 'ES', category: 'GOLD' },
  { id: 'd3', firstName: 'Nicklas', lastName: 'Nielsen', shortName: 'NIE', countryCode: 'DK', category: 'GOLD' },

  // Toyota #7
  { id: 'd4', firstName: 'Kamui', lastName: 'Kobayashi', shortName: 'KOB', countryCode: 'JP', category: 'PLATINUM' },
  { id: 'd5', firstName: 'Nyck', lastName: 'de Vries', shortName: 'DEV', countryCode: 'NL', category: 'PLATINUM' },
  { id: 'd6', firstName: 'Jose Maria', lastName: 'Lopez', shortName: 'LOP', countryCode: 'AR', category: 'PLATINUM' },

  // Porsche #6
  { id: 'd7', firstName: 'Kevin', lastName: 'Estre', shortName: 'EST', countryCode: 'FR', category: 'PLATINUM' },
  { id: 'd8', firstName: 'Andre', lastName: 'Lotterer', shortName: 'LOT', countryCode: 'DE', category: 'PLATINUM' },
  { id: 'd9', firstName: 'Laurens', lastName: 'Vanthoor', shortName: 'VAN', countryCode: 'BE', category: 'PLATINUM' },

  // Alpine #35
  { id: 'd10', firstName: 'Paul-Loup', lastName: 'Chatin', shortName: 'CHA', countryCode: 'FR', category: 'GOLD' },
  { id: 'd11', firstName: 'Ferdinand', lastName: 'Habsburg', shortName: 'HAB', countryCode: 'AT', category: 'GOLD' },
  { id: 'd12', firstName: 'Charles', lastName: 'Milesi', shortName: 'MIL', countryCode: 'FR', category: 'PLATINUM' },
];

export const mockEntries = [
  {
    id: 'e50',
    number: '50',
    team: 'Ferrari AF Corse',
    drivers: [mockDrivers[0], mockDrivers[1], mockDrivers[2]],
    class: 'HYPERCAR',
    manufacturer: 'Ferrari',
    car: '499P',
    currentDriver: mockDrivers[0],
  },
  {
    id: 'e7',
    number: '7',
    team: 'Toyota Gazoo Racing',
    drivers: [mockDrivers[3], mockDrivers[4], mockDrivers[5]],
    class: 'HYPERCAR',
    manufacturer: 'Toyota',
    car: 'GR010 HYBRID',
    currentDriver: mockDrivers[3],
  },
  {
    id: 'e6',
    number: '6',
    team: 'Porsche Penske Motorsport',
    drivers: [mockDrivers[6], mockDrivers[7], mockDrivers[8]],
    class: 'HYPERCAR',
    manufacturer: 'Porsche',
    car: '963',
    currentDriver: mockDrivers[6],
  },
  {
    id: 'e35',
    number: '35',
    team: 'Alpine Endurance Team',
    drivers: [mockDrivers[9], mockDrivers[10], mockDrivers[11]],
    class: 'HYPERCAR',
    manufacturer: 'Alpine',
    car: 'A424',
    currentDriver: mockDrivers[9],
  },
];

export const mockRaces = {
  'qatar-2025': {
    id: 'qatar-2025',
    name: '1812km of Qatar',
    championshipId: 'wec-2025',
    circuit: mockCircuits.lusail,
    startTime: '2025-02-28T13:00:00Z',
    endTime: '2025-02-28T19:00:00Z',
    status: 'RACING',
    session: 'RACE',
    entries: mockEntries,
    timingData: {
      raceId: 'qatar-2025',
      laps: 58,
      timeElapsed: '3:24:15',
      timeRemaining: '2:35:45',
      flagStatus: 'RACING',
      positions: [
        {
          position: 1,
          entryId: 'e50',
          number: '50',
          class: 'HYPERCAR',
          team: 'Ferrari AF Corse',
          currentDriver: mockDrivers[0],
          lapsCompleted: 58,
          lastLapTime: '1:48.234',
          bestLapTime: '1:47.892',
          sector1: '32.456',
          sector2: '41.234',
          sector3: '34.544',
          gapToLeader: '-',
          gapToAhead: '-',
          intervalToAhead: '-',
          pitStops: 2,
          inPit: false,
          crossing: 'NONE',
          lastPitTime: '1:23:45',
          lastPitDuration: '56.2',
          stintLaps: 18,
          tireCompound: 'SOFT',
        },
        {
          position: 2,
          entryId: 'e7',
          number: '7',
          class: 'HYPERCAR',
          team: 'Toyota Gazoo Racing',
          currentDriver: mockDrivers[3],
          lapsCompleted: 58,
          lastLapTime: '1:48.567',
          bestLapTime: '1:47.945',
          sector1: '32.567',
          sector2: '41.345',
          sector3: '34.655',
          gapToLeader: '+12.345',
          gapToAhead: '+12.345',
          intervalToAhead: '+12.345',
          pitStops: 2,
          inPit: false,
          crossing: 'NONE',
          lastPitTime: '1:25:12',
          lastPitDuration: '54.8',
          stintLaps: 17,
          tireCompound: 'SOFT',
        },
        {
          position: 3,
          entryId: 'e6',
          number: '6',
          class: 'HYPERCAR',
          team: 'Porsche Penske Motorsport',
          currentDriver: mockDrivers[6],
          lapsCompleted: 58,
          lastLapTime: '1:48.891',
          bestLapTime: '1:48.012',
          sector1: '32.678',
          sector2: '41.456',
          sector3: '34.757',
          gapToLeader: '+28.789',
          gapToAhead: '+16.444',
          intervalToAhead: '+16.444',
          pitStops: 2,
          inPit: false,
          crossing: 'NONE',
          lastPitTime: '1:26:34',
          lastPitDuration: '57.1',
          stintLaps: 16,
          tireCompound: 'MEDIUM',
        },
        {
          position: 4,
          entryId: 'e35',
          number: '35',
          class: 'HYPERCAR',
          team: 'Alpine Endurance Team',
          currentDriver: mockDrivers[9],
          lapsCompleted: 57,
          lastLapTime: '1:49.234',
          bestLapTime: '1:48.567',
          sector1: '32.890',
          sector2: '41.678',
          sector3: '34.890',
          gapToLeader: '+1 LAP',
          gapToAhead: '+1 LAP',
          intervalToAhead: '+1 LAP',
          pitStops: 3,
          inPit: false,
          crossing: 'NONE',
          lastPitTime: '0:45:23',
          lastPitDuration: '1:12.4',
          stintLaps: 12,
          tireCompound: 'SOFT',
        },
      ],
    },
  },
};
