[package]
name = "cli"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
motorsport = { path = "../motorsport" }
csv = "1.3"
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = "3.0"
