[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
motorsport = { path = "../motorsport" }
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
tempfile = "3.0"
